name: o2-tatneft

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.3
        with:
          python-version: 3.11

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      
      - name: Setup dependencies
        run: poetry install
      
      - name: Run Poetry
        run: poetry run flake8 .
